CATEGORIES = [{
    "title": "Разработка и IT",
    "code": "programming",
    "subcategories": [
        {"id": 37, "title": "Веб-программирование", "code": "web-development"},
        {"id": 1, "title": "Прикладное программирование", "code": "desktop-development"},
        {"id": 279, "title": "Разработка Чат-ботов", "code": "script-development"},
        {"id": 225, "title": "Google Android", "code": "mobile-development"},
        {"id": 97, "title": "1С-программирование", "code": "other-development"},
        {"id": 280, "title": "Парсинг данных", "code": "script-development"},
        {"id": 5, "title": "Базы данных", "code": "databases-development"},
        {"id": 226, "title": "iOS", "code": "mobile-development"},
        {"id": 297, "title": "Создание скриптов", "code": "script-development"},
        {"id": 2, "title": "Системное программирование", "code": "desktop-development"},
        {"id": 222, "title": "Разработка CRM и ERP", "code": "other-development"},
        {"id": 6, "title": "Программирование для сотовых телефонов и КПК", "code": "mobile-development"},
        {"id": 296, "title": "Машинное обучение", "code": "ai-blockchain"},
        {"id": 221, "title": "Плагины/Сценарии/Утилиты", "code": "script-development"},
        {"id": 223, "title": "Интерактивные приложения", "code": "web-development"},
        {"id": 161, "title": "Встраиваемые системы", "code": "other-development"},
        {"id": 278, "title": "Blockchain", "code": "ai-blockchain"},
        {"id": 229, "title": "Прототипирование", "code": "other-development"},
        {"id": 473, "title": "Laravel", "code": "web-development"},
        {"id": 474, "title": "Vue", "code": "web-development"},
        {"id": 355, "title": "Yii", "code": "web-development"},
        {"id": 9, "title": "Веб-программирование", "code": "web-development"},
        {"id": 27, "title": "Сайт «под ключ»", "code": "web-development"},
        {"id": 8, "title": "Верстка", "code": "web-development"},
        {"id": 282, "title": "Тильда", "code": "web-development"},
        {"id": 276, "title": "Лендинги", "code": "web-development"},
        {"id": 81, "title": "QA (тестирование)", "code": "testing-audit"},
        {"id": 217, "title": "Интернет-магазины", "code": "web-development"},
        {"id": 275, "title": "WordPress", "code": "web-development"},
        {"id": 220, "title": "Доработка сайтов", "code": "web-development"},
        {"id": 86, "title": "CMS (системы управления)", "code": "web-development"},
        {"id": 218, "title": "Проектирование", "code": "web-development"},
        {"id": 281, "title": "1С Битрикс", "code": "web-development"},
        {"id": 307, "title": "Zero-coding", "code": "web-development"},
        {"id": 349, "title": "React", "code": "web-development"},
        {"id": 219, "title": "Юзабилити-анализ", "code": "testing-audit"},
        {"id": 72, "title": "Wap/PDA-сайты", "code": "web-development"},
        {"id": 87, "title": "Флеш-сайты", "code": "web-development"},
        {"id": 347, "title": "Laravel", "code": "web-development"},
        {"id": 348, "title": "Vue", "code": "web-development"},
        {"id": 350, "title": "Node", "code": "web-development"},
        {"id": 353, "title": "Joomla", "code": "web-development"},
        {"id": 443, "title": "Webflow", "code": "web-development"},
        {"id": 351, "title": "OpenCart", "code": "web-development"},
        {"id": 352, "title": "MODx", "code": "web-development"},
        {"id": 354, "title": "Magento", "code": "web-development"},
        {"id": 475, "title": "Yii", "code": "web-development"},
    ],
}, {
    "title": "Дизайн и графика",
    "code": "design",
    "subcategories": [
        {"id": 46, "title": "Логотипы", "code": "design-branding"},
        {"id": 3, "title": "Дизайн сайтов", "code": "design-web-mobile"},
        {"id": 172, "title": "Дизайн сайтов", "code": "design-web-mobile"},
        {"id": 42, "title": "Фирменный стиль", "code": "design-branding"},
        {"id": 18, "title": "Фирменный стиль", "code": "design-branding"},
        {"id": 49, "title": "Полиграфический дизайн", "code": "design-layout"},
        {"id": 300, "title": "UI/UX дизайн", "code": "design-interfaces"},
        {"id": 19, "title": "Презентации", "code": "design-presentations"},
        {"id": 517, "title": "Презентации", "code": "design-presentations"},
        {"id": 51, "title": "Дизайн упаковки", "code": "design-layout"},
        {"id": 238, "title": "Инфографика", "code": "design-presentations"},
        {"id": 444, "title": "Figma", "code": "design-web-mobile"},
        {"id": 35, "title": "Интерфейсы", "code": "design-interfaces"},
        {"id": 45, "title": "Баннеры", "code": "design-outdoor"},
        {"id": 146, "title": "Интерьеры", "code": "design-interior-exterior"},
        {"id": 50, "title": "Интерьеры", "code": "design-interior-exterior"},
        {"id": 283, "title": "Лэндинги", "code": "design-web-mobile"},
        {"id": 239, "title": "Мобильные приложения", "code": "design-web-mobile"},
        {"id": 502, "title": "Редизайн сайтов", "code": "design-web-mobile"},
        {"id": 397, "title": "Редизайн сайтов", "code": "design-web-mobile"},
        {"id": 500, "title": "Дизайн для соцсетей", "code": "design-social-media"},
        {"id": 93, "title": "Архитектура", "code": "design-interior-exterior"},
        {"id": 90, "title": "Полиграфическая верстка", "code": "design-layout"},
        {"id": 52, "title": "Промышленный дизайн", "code": "design-branding"},
        {"id": 414, "title": "Промышленный дизайн", "code": "design-branding"},
        {"id": 78, "title": "Разработка шрифтов", "code": "design-fonts"},
        {"id": 75, "title": "Наружная реклама", "code": "design-outdoor"},
        {"id": 501, "title": "Дизайн для маркетплейсов", "code": "design-social-media"},
        {"id": 143, "title": "Ландшафтный дизайн/Генплан", "code": "design-interior-exterior"},
        {"id": 128, "title": "Дизайн выставочных стендов", "code": "design-outdoor"},
        {"id": 273, "title": "Верстка электронных изданий", "code": "design-layout"},
        {"id": 91, "title": "2D Персонажи", "code": "design-art"},
        {"id": 168, "title": "3D Иллюстрации", "code": "design-3d-graphics"},
        {"id": 306, "title": "NFT-арт", "code": "design-art"},
        {"id": 15, "title": "Векторная графика", "code": "design-art"},
        {"id": 190, "title": "Визуализация/3D", "code": "design-3d-graphics"},
        {"id": 47, "title": "Иконки", "code": "design-web-mobile"},
        {"id": 379, "title": "Книжные иллюстрации", "code": "design-art"},
        {"id": 88, "title": "Комиксы", "code": "design-art"},
        {"id": 383, "title": "Обложки для видео", "code": "design-social-media"},
        {"id": 409, "title": "Обложки для соцсетей", "code": "design-social-media"},
        {"id": 157, "title": "Пиксел-арт", "code": "design-art"},
        {"id": 48, "title": "Рисунки и иллюстрации", "code": "design-art"},
        {"id": 400, "title": "Техническая иллюстрация", "code": "design-art"},
        {"id": 522, "title": "3D графика", "code": "design-3d-graphics"},
        {"id": 518, "title": "Email оформление", "code": "design-web-mobile"},
        {"id": 527, "title": "POS-материалы", "code": "design-outdoor"},
        {"id": 531, "title": "Брендбук", "code": "design-branding"},
        {"id": 523, "title": "Визитки", "code": "design-branding"},
        {"id": 530, "title": "Гайдлайн", "code": "design-branding"},
        {"id": 519, "title": "Корпоративная графика", "code": "design-branding"},
        {"id": 529, "title": "Логобук", "code": "design-branding"},
        {"id": 513, "title": "Логотип", "code": "design-branding"},
        {"id": 514, "title": "Маскот", "code": "design-branding"},
        {"id": 528, "title": "Мокапы", "code": "design-branding"},
        {"id": 510, "title": "Нейминг", "code": "design-branding"},
        {"id": 524, "title": "Открытки/приглашения", "code": "design-branding"},
        {"id": 526, "title": "Пластиковые карты", "code": "design-branding"},
        {"id": 525, "title": "Полиграфия", "code": "design-branding"},
        {"id": 517, "title": "Презентации", "code": "design-branding"},
        {"id": 511, "title": "Слоганы/дескрипторы", "code": "design-branding"},
        {"id": 521, "title": "Типографика", "code": "design-layout"},
        {"id": 512, "title": "Товарный знак", "code": "design-branding"},
        {"id": 533, "title": "Упаковка", "code": "design-layout"},
        {"id": 532, "title": "Фирменная одежда", "code": "design-layout"},
        {"id": 520, "title": "Фотостиль", "code": "design-branding"},
        {"id": 515, "title": "Цветовая схема", "code": "design-branding"},
        {"id": 516, "title": "Шрифты", "code": "design-fonts"},
        {"id": 314, "title": "Дизайн карточек товаров", "code": "design-social-media"},
    ]
}, {
    "title": "Маркетинг и реклама",
    "code": "marketing",
    "subcategories": [
        {"id": 334, "title": "Арбитраж трафика", "code": "marketing-analytics"},
        {"id": 333, "title": "Аудит сайта", "code": "marketing-analytics"},
        {"id": 335, "title": "Аутрич", "code": "marketing-outreach"},
        {"id": 100, "title": "Контент", "code": "marketing-content"},
        {"id": 336, "title": "Крауд-маркетинг", "code": "marketing-outreach"},
        {"id": 34, "title": "Поисковые системы", "code": "marketing-seo"},
        {"id": 99, "title": "Продажа ссылок", "code": "marketing-seo"},
        {"id": 330, "title": "Продвижение в Google", "code": "marketing-seo"},
        {"id": 331, "title": "Продвижение в Яндексе", "code": "marketing-seo"},
        {"id": 329, "title": "Продвижение за рубежом", "code": "marketing-other"},
        {"id": 328, "title": "Продвижение сайтов", "code": "marketing-seo"},
        {"id": 332, "title": "Управление репутацией", "code": "marketing-pr"},
        {"id": 284, "title": "Email-маркетинг", "code": "marketing-marketing"},
        {"id": 509, "title": "Google Ads", "code": "marketing-seo"},
        {"id": 506, "title": "Instagram", "code": "marketing-smm"},
        {"id": 508, "title": "myTarget", "code": "marketing-smm"},
        {"id": 59, "title": "PR-менеджмент", "code": "marketing-pr"},
        {"id": 292, "title": "SERM (управление репутацией)", "code": "marketing-pr"},
        {"id": 245, "title": "SMM (маркетинг в соцсетях)", "code": "marketing-smm"},
        {"id": 188, "title": "SMO", "code": "marketing-smm"},
        {"id": 505, "title": "Telegram", "code": "marketing-smm"},
        {"id": 346, "title": "Анализ конкурентов", "code": "marketing-analytics"},
        {"id": 42, "title": "Бизнес-планы", "code": "marketing-other"},
        {"id": 507, "title": "ВКонтакте", "code": "marketing-smm"},
        {"id": 66, "title": "Исследования", "code": "marketing-other"},
        {"id": 118, "title": "Контекстная реклама", "code": "marketing-ppc"},
        {"id": 247, "title": "Креатив", "code": "marketing-other"},
        {"id": 294, "title": "Маркетинговая стратегия", "code": "marketing-marketing"},
        {"id": 21, "title": "Медиапланирование", "code": "marketing-other"},
        {"id": 248, "title": "Продажи и генерация лидов", "code": "marketing-marketing"},
        {"id": 295, "title": "Реклама у блогеров", "code": "marketing-outreach"},
        {"id": 56, "title": "Рекламные концепции", "code": "marketing-marketing"},
        {"id": 67, "title": "Сбор и обработка информации", "code": "marketing-analytics"},
        {"id": 289, "title": "Таргетированная реклама", "code": "marketing-ppc"},
        {"id": 250, "title": "Телемаркетинг и продажи по телефону", "code": "marketing-marketing"},
        {"id": 503, "title": "Яндекс Бизнес", "code": "marketing-seo"},
        {"id": 504, "title": "Яндекс Директ", "code": "marketing-seo"},
        {"id": 345, "title": "3D модели товаров", "code": "marketing-marketplaces"},
        {"id": 343, "title": "Alibaba", "code": "marketing-marketplaces"},
        {"id": 344, "title": "Aliexpress", "code": "marketing-marketplaces"},
        {"id": 340, "title": "KazanExpress", "code": "marketing-marketplaces"},
        {"id": 341, "title": "Lamoda", "code": "marketing-marketplaces"},
        {"id": 338, "title": "Ozon", "code": "marketing-marketplaces"},
        {"id": 317, "title": "SEO-оптимизация карточек", "code": "marketing-marketplaces"},
        {"id": 337, "title": "Wildberries", "code": "marketing-marketplaces"},
        {"id": 472, "title": "Авито Молл", "code": "marketing-marketplaces"},
        {"id": 313, "title": "Аналитика конкурентов и продаж", "code": "marketing-analytics"},
        {"id": 438, "title": "Бухгалтер для селлеров", "code": "marketing-marketplaces"},
        {"id": 316, "title": "Ведение кабинета продавца", "code": "marketing-marketplaces"},
        {"id": 315, "title": "Выход на маркетплейсы", "code": "marketing-marketplaces"},
        {"id": 342, "title": "МегаМаркет", "code": "marketing-marketplaces"},
        {"id": 285, "title": "Продвижение на маркетплейсах", "code": "marketing-marketplaces"},
        # {"id": 312, "title": "Тексты для карточек товаров", "code": "marketing-content"},
        {"id": 339, "title": "Яндекс.Маркет", "code": "marketing-marketplaces"},
        {"id": 393, "title": "Продвижение в AppStore", "code": "marketing-other"},
        {"id": 394, "title": "Продвижение в Google Play Store", "code": "marketing-other"},
        {"id": 396, "title": "Продвижение в Huawei AppGallery", "code": "marketing-other"},
        {"id": 395, "title": "Продвижение в RuStore", "code": "marketing-other"},
        {"id": 454, "title": "SEO оптимизация контента", "code": "marketing-seo"},
        {"id": 467, "title": "Аналитика магазина", "code": "marketing-analytics"},
        # {"id": 468, "title": "Тексты для магазинов", "code": "marketing-marketplaces"},
        {"id": 456, "title": "Товарные карточки", "code": "marketing-marketplaces"},
        {"id": 339, "title": "Яндекс.Маркет", "code": "marketing-marketplaces"}
    ]
}, {
    "title": "Аудио и видео",
    "code": "audio-video",
    "subcategories": [
        {"id": 25, "title": "Аудиомонтаж", "code": "audio"},
        {"id": 73, "title": "Видеодизайн", "code": "video"},
        {"id": 264, "title": "Видеоинфографика", "code": "video"},
        {"id": 117, "title": "Видеомонтаж", "code": "video"},
        {"id": 266, "title": "Видеопрезентации", "code": "video"},
        {"id": 163, "title": "Видеосъемка", "code": "video"},
        {"id": 437, "title": "Визуальные эффекты (VFX)", "code": "video"},
        {"id": 162, "title": "Диктор", "code": "audio"},
        {"id": 24, "title": "Музыка/Звуки", "code": "audio"},
        {"id": 274, "title": "Промышленная фотосъемка", "code": "photo"},
        {"id": 268, "title": "Режиссура", "code": "audio"},
        {"id": 112, "title": "Рекламная/Постановочная фотография", "code": "photo"},
        {"id": 55, "title": "Ретуширование/Коллажи", "code": "photo"},
        {"id": 201, "title": "Создание субтитров", "code": "video"},
        {"id": 115, "title": "Фото Архитектуры/Интерьеров", "code": "photo"},
        {"id": 71, "title": "Художественная/Арт фотография", "code": "photo"}
    ]
}]

SUBCATEGORIES_REVERSE = {
    subcategory["id"]: subcategory["code"]
    for category in CATEGORIES
    for subcategory in category["subcategories"]
}
