# Generated by Django 5.0.6 on 2024-05-19 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.usersubscription'),
        ),
    ]
