# Generated by Django 5.0.6 on 2024-05-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_telegramuser_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='hourly_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
