# Generated by Django 5.0.6 on 2024-05-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegramuser_hourly_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecategory',
            options={'verbose_name': 'Категория источника', 'verbose_name_plural': 'Категории источников'},
        ),
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='sourcecategory',
            unique_together={('source', 'code')},
        ),
    ]
