# Generated by Django 5.0.6 on 2024-05-20 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sourcecategory_options_alter_source_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecategory',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.source'),
        ),
    ]
