# Generated by Django 5.0.6 on 2024-05-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sourcecategory_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gptprompt',
            old_name='prompt',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='gptprompt',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='core.gptmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='gptprompt',
            unique_together={('model', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('source', 'project_id')},
        ),
    ]
