# Generated by Django 5.0.6 on 2024-05-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subscriptiongptlimits_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptprompt',
            name='json_format',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
