# Generated by Django 5.0.6 on 2024-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gptprompt_json_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency_symbol',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
