# Generated by Django 5.0.6 on 2024-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_currency_symbol_subcategory_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='stop_words',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
