# Generated by Django 5.0.6 on 2024-05-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_telegramuser_stop_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
