# Generated by Django 5.0.6 on 2024-05-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_project_price_max_alter_project_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
