# Generated by Django 5.0.6 on 2024-05-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_categorysubscription_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='keywords',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
