# Generated by Django 5.0.6 on 2024-05-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_telegramuser_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gptprompt',
            old_name='json_format',
            new_name='response_format',
        ),
        migrations.AddField(
            model_name='subscription',
            name='days_count',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gpt_request_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='gpt_request_limit',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='SubscriptionGPTLimits',
        ),
    ]
