# Generated by Django 5.0.6 on 2024-05-30 22:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_json_format_gptprompt_response_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcesubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GPTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('completed', 'Выполнен'), ('delivered', 'Отправлен пользователю')], default='accepted', max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.CharField(blank=True, max_length=512, null=True)),
                ('summary', models.CharField(blank=True, max_length=1024, null=True)),
                ('experience', models.CharField(blank=True, max_length=1024, null=True)),
                ('hourly_rate', models.IntegerField(blank=True, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_requests', to='core.project')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_requests', to='core.gptprompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_requests', to='core.telegramuser')),
            ],
        ),
    ]
