# Generated by Django 5.0.6 on 2024-06-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_categorysubscription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user_subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='gpt_request_limit',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='gpt_request_limit',
        ),
        migrations.AddField(
            model_name='gptrequest',
            name='tokens',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='gptrequest',
            name='type',
            field=models.CharField(choices=[('order_response', 'Отклик'), ('order_analyze', 'Анализ'), ('sale_plan', 'План продажи')], default='order_analyze', max_length=100),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='balance',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='core.telegramuser'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referrer_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='subscription_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gptrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gpt_requests', to='core.project'),
        ),
        migrations.AlterField(
            model_name='gptrequest',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gpt_requests', to='core.gptprompt'),
        ),
        migrations.AlterField(
            model_name='gptrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('completed', 'Выполнен'), ('delivered', 'Отправлен пользователю')], default='accepted', max_length=100),
        ),
        migrations.AlterField(
            model_name='gptrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gpt_requests', to='core.telegramuser'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(verbose_name='Цена (в токенах)'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('completed', 'Выполнен')], default='accepted', max_length=10)),
                ('tokens', models.IntegerField(default=0)),
                ('payment_uuid', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('subscription', 'Подписка'), ('gpt_request', 'AI-запрос')], default='gpt_request', max_length=100)),
                ('gpt_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.gptrequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.project')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.telegramuser')),
            ],
        ),
        migrations.DeleteModel(
            name='SourceCategory',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
