# Generated by Django 5.0.6 on 2024-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_usersubscription_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='balance',
            new_name='tokens',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.AddField(
            model_name='subscription',
            name='tokens',
            field=models.IntegerField(default=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
