# Generated by Django 5.0.6 on 2024-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_balance_telegramuser_tokens_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='referrer_processed',
            new_name='registration_completed',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='referral_code',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='tokens',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
