# Generated by Django 5.0.6 on 2024-06-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_referrer_processed_telegramuser_registration_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='response',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_uuid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('generated', 'Сформирован'), ('completed', 'Выполнен')], default='accepted', max_length=10),
        ),
    ]
