# Generated by Django 5.0.6 on 2024-06-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_payment_payment_payment_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotent_uuid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
