# Generated by Django 5.0.6 on 2024-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_gptrequest_tokens_gptprompt_tokens_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gptprompt',
            unique_together={('model', 'category', 'type')},
        ),
    ]
