# Generated by Django 5.0.6 on 2024-06-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_transaction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delete_message_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
