# Generated by Django 5.0.6 on 2024-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
