# Generated by Django 5.0.6 on 2024-06-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_gptrequest_input_tokens_gptrequest_output_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
