# Generated by Django 5.0.6 on 2024-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_telegramuser_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
