# Generated by Django 5.0.6 on 2024-06-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_telegramuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptrequest',
            name='gpt_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
