# Generated by Django 5.0.6 on 2024-06-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_gptrequest_gpt_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptrequest',
            name='gpt_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
