# Generated by Django 5.0.6 on 2024-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_gptrequest_gpt_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='telegram_group_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
